I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 92, in script
    여주 "아 @%!ㅃ#$ 망했네."
ValueError: unsupported format character '!' (0x21) at index 4

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 92, in script
    여주 "아 @%!ㅃ#$ 망했네."
  File "C:\Users\Win10\Downloads\renpy-8.2.1-sdk\renpy\ast.py", line 2557, in execute
    Say.execute(self)
  File "C:\Users\Win10\Downloads\renpy-8.2.1-sdk\renpy\ast.py", line 615, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\Win10\Downloads\renpy-8.2.1-sdk\renpy\exports.py", line 1482, in say
    what = what % tag_quoting_dict
ValueError: unsupported format character '!' (0x21) at index 4

Windows-10-10.0.22631 AMD64
Ren'Py 8.2.1.24030407
ITShow 1.0
Mon Jun 17 14:55:19 2024
