I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 125, in script
    "이곳은 바다가 보이는 학교,푸른 고등학교."
  File "game/script.rpy", line 125, in script
    "이곳은 바다가 보이는 학교,푸른 고등학교."
  File "renpy/common/000window.rpy", line 122, in _window_auto_callback
    _window_show(auto=True)
  File "renpy/common/000window.rpy", line 70, in _window_show
    renpy.with_statement(trans)
ShaderError: b'\x06'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\Win10\Downloads\renpy-8.2.1-sdk\renpy\bootstrap.py", line 359, in bootstrap
    renpy.main.main()
  File "C:\Users\Win10\Downloads\renpy-8.2.1-sdk\renpy\main.py", line 635, in main
    run(restart)
  File "C:\Users\Win10\Downloads\renpy-8.2.1-sdk\renpy\main.py", line 145, in run
    renpy.execution.run_context(True)
  File "C:\Users\Win10\Downloads\renpy-8.2.1-sdk\renpy\execution.py", line 955, in run_context
    context.run()
  File "game/script.rpy", line 125, in script
    "이곳은 바다가 보이는 학교,푸른 고등학교."
  File "lib/python3.9/future/utils/__init__.py", line 444, in raise_
  File "game/script.rpy", line 125, in script
    "이곳은 바다가 보이는 학교,푸른 고등학교."
  File "C:\Users\Win10\Downloads\renpy-8.2.1-sdk\renpy\ast.py", line 2557, in execute
    Say.execute(self)
  File "C:\Users\Win10\Downloads\renpy-8.2.1-sdk\renpy\ast.py", line 585, in execute
    statement_name("say")
  File "C:\Users\Win10\Downloads\renpy-8.2.1-sdk\renpy\ast.py", line 52, in statement_name
    i(name)
  File "renpy/common/000window.rpy", line 122, in _window_auto_callback
    _window_show(auto=True)
  File "renpy/common/000window.rpy", line 70, in _window_show
    renpy.with_statement(trans)
  File "C:\Users\Win10\Downloads\renpy-8.2.1-sdk\renpy\exports.py", line 1781, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "C:\Users\Win10\Downloads\renpy-8.2.1-sdk\renpy\display\core.py", line 1548, in do_with
    return self.interact(trans_pause=True,
  File "C:\Users\Win10\Downloads\renpy-8.2.1-sdk\renpy\display\core.py", line 2165, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "C:\Users\Win10\Downloads\renpy-8.2.1-sdk\renpy\display\core.py", line 2793, in interact_core
    if renpy.display.draw.update(force=self.display_reset):
  File "gl2draw.pyx", line 681, in renpy.gl2.gl2draw.GL2Draw.update
  File "gl2draw.pyx", line 615, in renpy.gl2.gl2draw.GL2Draw.on_resize
  File "gl2texture.pyx", line 75, in renpy.gl2.gl2texture.TextureLoader.init
  File "C:\Users\Win10\Downloads\renpy-8.2.1-sdk\renpy\gl2\gl2shadercache.py", line 278, in get
    rv.load()
  File "gl2shader.pyx", line 241, in renpy.gl2.gl2shader.Program.load
ShaderError: b'\x06'

Windows-10-10.0.22631 AMD64
Ren'Py 8.2.1.24030407
ITShow 1.0
Wed Jun 19 16:07:22 2024
